name: Patch Hangar Page
author: Tamion
description: Automatically Patches your Projects Hangar Page with your README.md
inputs:
  hangar-api-key:
    description: 'Your hangar api key'
    required: true
  hangar-slug:
    description: 'Project Slug of the Project'
    required: true
on:
  push:
    paths:
      - 'README.md'
    branches:
      - master
      - main
jobs:
  patch-hangar-page:
    runs-on: ubuntu-latest
    steps:
    - name: Get JWT
      id: getjwt
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://hangar.papermc.io/api/v1/authenticate?apiKey=${{ github.event.inputs.hangar-api-key }}'
        method: 'POST'
    - name: Get ReadMe
      id: getreadme
      uses: jaywcjlove/github-action-read-file@main
      with:
        path: README.md
    - name: Patch Page
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://hangar.papermc.io/api/v1/pages/editmain/${{ github.event.inputs.hangar-slug }}'
        method: 'PATCH'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "${{ fromJson(steps.getjwt.outputs.response).token }}"}'
        data: '${{ steps.getreadme.outputs.content }}'
